apiVersion: v1
kind: Service
metadata:
  name: users-be
  namespace: skillsier
  labels:
    app: users-be
    component: backend
spec:
  type: ClusterIP
  selector:
    app: users-be
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  sessionAffinity: None