apiVersion: v1
kind: ConfigMap
metadata:
  name: web-fe-config
  namespace: skillsier
data:
  NEXT_PUBLIC_API_URL: "https://api.skillsier.com/api"
  NEXT_PUBLIC_KEYCLOAK_URL: "https://keycloak.skillsier.com"
  NEXT_PUBLIC_KEYCLOAK_REALM: "skillsier"
  NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: "skillsier-fe"
  NEXT_PUBLIC_APP_URL: "https://skillsier.com"