apiVersion: v1
kind: Secret
metadata:
  name: web-fe-secrets
  namespace: skillsier
type: Opaque
stringData:
  KEYCLOAK_CLIENT_SECRET: "<your-keycloak-client-secret>"
  KEYCLOAK_MGMT_CLIENT_SECRET: "<your-keycloak-mgmt-secret>"
  KEYCLOAK_MGMT_CLIENT_ID: "skillsier-bff"
  KEYCLOAK_ISSUER_URL: "https://keycloak.skillsier.com/realms/skillsier"