apiVersion: v1
kind: Service
metadata:
  name: <service>-be-postgres-external
  namespace: <k8s_namespace>
  labels:
    app: <service>-be-postgres
spec:
  type: NodePort
  selector:
    app: <service>-be-postgres
  ports:
    - name: pg
      port: 5432
      targetPort: 5432
      nodePort: 30432