apiVersion: v1
kind: Secret
metadata:
  name: <service>-be-postgres
  namespace: <k8s_namespace>
  labels:
    app: <service>-be-postgres
type: Opaque
stringData:
  POSTGRES_DB: "<db_name>"
  POSTGRES_USER: "<db_user>"
  POSTGRES_PASSWORD: "CHANGE_ME_IN_PRODUCTION"