apiVersion: v1
kind: Service
metadata:
  name: <service>-be
  namespace: <k8s_namespace>
  labels:
    app: <service>-be
    component: backend
spec:
  type: ClusterIP
  selector:
    app: <service>-be
  ports:
    - name: http
      port: 80
      targetPort: <service_port>
      protocol: TCP
  sessionAffinity: None