apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: skillsier

bases:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml

configMapGenerator:
  - name: users-be-config
    behavior: merge
    literals:
      - app.environment=development
      - app.log_level=debug
      - database.auto_migrate=true

replicas:
  - name: users-be
    count: 1

commonLabels:
  environment: local

commonAnnotations:
  deployment.environment: local
  config.reload: enabled