apiVersion: v1
kind: Service
metadata:
  name: users-be
  namespace: skillsier
  labels:
    app: users-be
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: users-be
---
apiVersion: v1
kind: Service
metadata:
  name: users-be-external
  namespace: skillsier
  labels:
    app: users-be
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30800
      protocol: TCP
  selector:
    app: users-be