apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: users-be-postgres-allow-app
  namespace: skillsier
  labels:
    app: users-be-postgres
spec:
  podSelector:
    matchLabels:
      app: users-be-postgres
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 5432